sudo: required
services:
  - docker

before_install:
  - docker build -t maistrenkoanton/docker-kubernetes -f frontend/Dockerfile.dev .

script:
  - docker run maistrenkoanton/docker-kubernetes npm run test